JS - Serialize/Deseralie game state
Pixel-Pushers-1/MonoZelda pull request #121
Opened 2024-11-17 23:41 UTC by bitblip

- `F5` to quick-save
- `F9` to quick-load

You can quick-load from the main menu

2024-11-22 15:26 UTC, bitblip commented
I had to rework the map widget a little to be compatible with saving. The trick is to look to PlayerState for map state.

2024-11-23 20:29 UTC, xsedim requested changes
Overall great work in implementing this feature which required a good deal of refactoring and keeping good code quality in mind.

One issue I found: saving from the starting room does not correctly store Link's starting position. To replicate, start the game, quick save without leaving the starting room, and then quick load from any room. I believe it is because Link's starting position is stored based on the door he entered a room from, but he never enters a door before saving so his position is set to (0, 0) outside the room.

Otherwise, the following features are correctly saved and loaded from my testing:
- Starting room
- Items (rupees, keys, bombs)
- Opened doors (key doors, diamond doors, bombable walls)
- Killed enemies
- Collected items (map, compass, keys, potion, boomerang, bow, triforce)
- Player health
- Equipped projectile
- Player map marker

2024-11-23 20:29 UTC, xsedim commented on MonoZelda/UI/HUDMapWidget.cs
> +
These should ideally only be called when the value changes, not every single frame, but they're small methods so this is not much of a performance hit.

2024-11-23 20:29 UTC, xsedim commented on MonoZelda/Save/SaveState.cs
> +    }
I believe this framework will be good for maintainability make it easy to add more saveable data in the future (RPG elements for sprint 5 like player level and XP).

2024-11-28 18:54 UTC, xsedim approved these changes
Tested — looks good

2024-11-28 18:54 UTC, merged